/*********************************************************************
 * Name:      	main.cpp
 * Purpose:   	Implements simple wxWidgets application with GUI
 * 				created using wxFormBuilder.
 * Author:
 * Created:
 * Copyright:
 * License:   	wxWidgets license (www.wxwidgets.org)
 *
 * Notes:		Note that all GUI creation code is implemented in
 * 				gui.cpp source file which is generated by wxFormBuilder.
 *********************************************************************/

// main wxWidgets header file
#include <wx/wx.h>
// gui classes generated by wxFormBuilder
#include "gui.h"
#include "wxUrho3D.h"

////////////////////////////////////////////////////////////////////////////////
// application class declaration
////////////////////////////////////////////////////////////////////////////////

class MainApp : public wxApp
{
public:
    virtual bool OnInit();
    Urho3D::SharedPtr<Urho3D::Context> context_;
};

// declare global static function wxGetApp()
DECLARE_APP(MainApp)


// initialize the application
IMPLEMENT_APP(MainApp)

////////////////////////////////////////////////////////////////////////////////
// application class implementation
////////////////////////////////////////////////////////////////////////////////

bool MainApp::OnInit()
{
    context_ = new Urho3D::Context();
    SetTopWindow( new wxUrho3D( NULL,context_ ) );
    GetTopWindow()->Show();
    
    // true = enter the main loop
    return true;
}


